[build.environment]
HUGO_VERSION = "0.140.0"
TZ = "Asia/Kolkata"

[build]
publish = "public"
command = "hugo --gc --minify --config hugo.toml"

[[redirects]]
  from = "/blog/26-openai-operator-prompt"
  to = "/blog/openai-operator-prompt"
  status = 301
  force = true

[[redirects]]
  from = "/blog/:tag"
  to = "/tags/:tag"
  status = 301
  force = true

[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 200

[[redirects]]
  from = "/rss"
  to = "/feed.xml"
  status = 200
